name: (adv.)Build Ladybird Browser

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            autoconf autoconf-archive automake build-essential ccache cmake curl \
            fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config \
            qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip \
            libpulse-dev qt6-multimedia-dev xvfb mesa-utils libegl-dev libglx-dev libosmesa6

      - name: Cache Build Files
        uses: actions/cache@v4
        with:
          path: |
            Build/
            ~/.ccache  # 🟢 Cache compiler outputs
          key: ${{ runner.os }}-ladybird-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ladybird-

      - name: Setup `ccache` for Faster Compilation
        run: |
          ccache --max-size=2G  # 🟢 Increase ccache size to 2GB for better caching
          echo "CC='ccache gcc'" >> $GITHUB_ENV
          echo "CXX='ccache g++'" >> $GITHUB_ENV

      - name: Setup Virtual Display (Xvfb)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Enable Software Rendering & Disable Vulkan
        run: |
          echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
          echo "MESA_LOADER_DRIVER_OVERRIDE=llvmpipe" >> $GITHUB_ENV
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV
          echo "QT_QPA_PLATFORMTHEME=qt5ct" >> $GITHUB_ENV

      - name: Build Ladybird Using `ladybird.sh`
        run: |
          chmod +x Meta/ladybird.sh
          ./Meta/ladybird.sh build

      - name: Show `ccache` Stats (Track Cache Efficiency)
        run: ccache --show-stats  # Keep cumulative stats

      - name: Debug Cached Files (Verify Cache is Working)
        run: find Build/ -type f | tee build-structure.txt

      - name: Upload Everything in `bin/`
        uses: actions/upload-artifact@v4
        with:
          name: Ladybird-All-Bin-Files
          path: |
            Build/**  # 🟢 Upload everything inside bin/
            build-structure.txt
          retention-days: 14
