name: Build Ladybird

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Specify the build type: Debug or Release'
        required: true
        default: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up vcpkg
        uses: microsoft/vcpkg-action@v2
        with:
          vcpkgDirectory: '${{ runner.temp }}/vcpkg'
          cleanAfterBuild: true

      - name: Install dependencies with vcpkg
        run: |
          vcpkg install simdutf
          vcpkg integrate install

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgl1-mesa-dev \
            ninja-build \
            qt6-base-dev \
            qt6-tools-dev-tools \
            qt6-multimedia-dev \
            qt6-wayland \
            ccache \
            nasm \
            g++-13

      - name: Configure build
        run: |
          cmake -S . -B build -GNinja \
            -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }} \
            -DCMAKE_TOOLCHAIN_FILE=${{ runner.temp }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build project
        run: |
          ninja -C build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-build
          path: build/
