name: Build Ladybird (Windows Native)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies via Chocolatey
        shell: pwsh
        run: |
          # Ensure Chocolatey is installed (it’s not preinstalled on Windows runners)
          Set-ExecutionPolicy Bypass -Scope Process -Force
          if (-Not (Get-Command choco -ErrorAction SilentlyContinue)) {
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }
          # Install Ninja and pkgconfiglite (needed for pkg-config support in some builds)
          choco install ninja pkgconfiglite -y
          Write-Output "Installed dependencies."
          Write-Output "Ninja version:"
          ninja --version

      - name: Build Ladybird using build script
        shell: pwsh
        run: |
          # Check if the build script exists and run it.
          if (Test-Path "./Meta/ladybird.sh") {
            Write-Output "Found build script. Starting build..."
            # This script is expected to build a Release version of Ladybird.
            ./Meta/ladybird.sh run ladybird
          } else {
            Write-Error "Build script not found: Meta/ladybird.sh"
            exit 1
          }

      - name: Verify Executable
        shell: pwsh
        run: |
          # Adjust the path below if your executable is generated in a different location.
          if (-Not (Test-Path "build\ladybird.exe")) {
            Write-Error "ERROR: ladybird.exe not found!"
            exit 1
          } else {
            Write-Output "Build successful! Executable located at build\ladybird.exe"
          }

      - name: Package Windows Executable
        shell: pwsh
        run: |
          Compress-Archive -Path "build\ladybird.exe" -DestinationPath "ladybird-windows.zip"
          Write-Output "Packaged ladybird-windows.zip"

      - name: Upload Windows Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-windows-executable
          path: ladybird-windows.zip
