name: Build Ladybird on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies via Chocolatey
      shell: pwsh
      run: |
        # Install Chocolatey if not already available, then install Ninja
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install ninja -y
        Write-Output "Ninja version:"
        ninja --version

    - name: Configure Build with CMake
      shell: pwsh
      run: |
        # The flag -DCMAKE_DISABLE_FIND_PACKAGE_PTHREAD=TRUE prevents CMake from trying to locate pthread
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_DISABLE_FIND_PACKAGE_PTHREAD=TRUE

    - name: Build Ladybird (With Progress Logging)
      shell: pwsh
      run: |
        # Start the build as a background job and pipe output to build.log
        $job = Start-Job -ScriptBlock {
          cmake --build build --config Release --parallel 4 2>&1 | Tee-Object -FilePath build.log
        }
        # While the build is running, output progress every 5 minutes to prevent timeout
        while ((Get-Job -Id $job.Id).State -eq 'Running') {
          Write-Output "Still compiling... (Preventing Timeout)"
          if (Test-Path build.log) {
             Get-Content build.log -Tail 15
          }
          Start-Sleep -Seconds 300
        }
        # Retrieve any remaining output from the build job
        Receive-Job -Id $job.Id

    - name: Verify Executable
      shell: pwsh
      run: |
        if (-Not (Test-Path -Path "build\ladybird.exe")) {
          Write-Error "ERROR: ladybird.exe not found!"
          exit 1
        } else {
          Write-Output "Build successful! Executable located at build\ladybird.exe"
        }

    - name: Package Windows Executable
      shell: pwsh
      run: |
        Compress-Archive -Path "build\ladybird.exe" -DestinationPath "ladybird-windows.zip"

    - name: Upload Windows Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ladybird-windows-binary
        path: ladybird-windows.zip
