name: Build and Package Ladybird (.deb)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf autoconf-archive automake build-essential ccache cmake curl \
            fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config \
            qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip dpkg-deb

      - name: Build Ladybird
        run: |
          # Ensure the build script is executable and run it.
          chmod +x Meta/ladybird.sh
          ./Meta/ladybird.sh run ladybird

      - name: Install Ladybird into Staging Directory
        run: |
          # Create the directory structure for the Debian package
          mkdir -p package/usr/bin
          mkdir -p package/DEBIAN
          # Copy the built binary to the staging directory.
          # Adjust the source path if your build script places the binary elsewhere.
          if [ -f Build/release/bin/Ladybird ]; then
            cp Build/release/bin/Ladybird package/usr/bin/ladybird
          elif [ -f Build/release/ladybird ]; then
            cp Build/release/ladybird package/usr/bin/ladybird
          else
            echo "ERROR: Built executable not found."
            exit 1
          fi

      - name: Create DEBIAN Control File
        run: |
          cat <<EOF > package/DEBIAN/control
          Package: ladybird-browser
          Version: 0.1.0
          Section: web
          Priority: optional
          Architecture: $(dpkg --print-architecture)
          Maintainer: Your Name <you@example.com>
          Description: Ladybird Browser - an experimental, independent web browser.
           Built from source as part of the LadybirdBrowser project.
          EOF

      - name: Build .deb Package
        run: |
          dpkg-deb --build package ladybird-browser_0.1.0_$(dpkg --print-architecture).deb

      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-deb
          path: ladybird-browser_0.1.0_$(dpkg --print-architecture).deb
