name: Build and Upload Ladybird Artifacts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.cpp', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            cmake \
            ninja-build \
            nasm \
            python3 \
            qt6-base-dev \
            qt6-multimedia-dev \
            qt6-tools-dev \
            qt6-wayland-dev \
            libgl1-mesa-dev

      - name: Configure build
        run: cmake -GNinja -B Build/release

      - name: Build Ladybird
        run: ninja -C Build/release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-build
          path: Build/release/bin/
